### ISSUE TITLE
LOGO PROPOSAL FOR PHOTOFEED

### ISSUE THREAD

**Issue by chrisjasonoswa** [code-with-sam/photofeed.club#10]
This is my logo proposal for Photofeed.club.

<h1>Logo Type</h1>

![photofeedlogotype](https://user-images.githubusercontent.com/38552359/40169480-ac1761d0-59f8-11e8-9f7c-7b516dd6e177.png)

<h1>Logo Icon</h1>

![photofeedlogoicon](https://user-images.githubusercontent.com/38552359/40169739-3fe8bed6-59f9-11e8-8030-40e70796471b.png)

<h1>Logo Idea</h1>

![photofeed](https://user-images.githubusercontent.com/38552359/40169850-83badbc6-59f9-11e8-959c-e49f50a2ca47.png)

<h1>Logo Mock-up</h1>

![photofeedmockup](https://user-images.githubusercontent.com/38552359/40170186-665b94ac-59fa-11e8-977a-0a66338eb71f.png)

That's it sir :) If you like it and want it to use for your page please tell me in discord @jason04#8287 or leave a comment so that I can provide the necessary files

**Comment by code-with-sam** [comment]
As mentioned in reply to your comment on the project blog.

> Thank you jason04 I appreciate the time and effort you've put into creating the logo proposal. As Photofeed is my offer to the @photofeed team and #photofeed community which already has established branding I am reluctant to create any of our own branding that would potentially confuse or misrepresent the project. I prefer to use a simple textmark while there is potential for partnership we the official project.

In future it's probably worth throwing a quick issue up asking the question first.
