### ISSUE TITLE
Doing Copywriting for PhotoFeed.club

### ISSUE THREAD

**Issue by curtwriter** [code-with-sam/photofeed.club#9]
Hello Sir Sambillingham. Nice work you have done with PhotoFeed.club. My name is curtwriter and I was hoping I could work on an About Us for Photofeed.club. I also noticed that your FAQ page was rift with errors and not comprehensive enough. Can you allow me handle the both copywriting? Thank you very much in anticipation.

**Comment by code-with-sam** [comment]
Hey @curtwriter have you used the site? Are you a photographer that uses the #photofeed hashtag to share your work?

**Comment by curtwriter** [comment]
I am not a photographer. Just a professional copywriter. I don't have the tools of the trade for photography yet.

**Comment by code-with-sam** [comment]
okay thanks I was hoping you had used the platform, feel free to reply with any additions you think are needed and I can re-open the issue if they are relevant.
